CREATE TABLE IF NOT EXISTS "met-galaxy_artwork" (
	"id" integer PRIMARY KEY NOT NULL,
	"objectId" integer NOT NULL,
	"title" text,
	"artist" text,
	"date" varchar(200),
	"medium" text,
	"primaryImage" varchar(1000),
	"localImageUrl" varchar(1000),
	"department" varchar(300),
	"culture" varchar(300),
	"createdAt" timestamp with time zone,
	"additionalImages" text,
	"objectUrl" varchar(1000),
	"isHighlight" boolean,
	"artistDisplayBio" text,
	"objectBeginDate" integer,
	"objectEndDate" integer,
	"creditLine" text,
	"classification" varchar(500),
	"artistNationality" varchar(500),
	"primaryImageSmall" varchar(1000),
	"description" text,
	"importedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
